-- MySQL Script generated by MySQL Workbench
-- Tue Feb 25 18:34:24 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema esquiar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema esquiar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `esquiar` DEFAULT CHARACTER SET utf8 ;
USE `esquiar` ;

-- -----------------------------------------------------
-- Table `esquiar`.`estaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquiar`.`estaciones` (
  `id_estaciones` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `ubicacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estaciones`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esquiar`.`pistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquiar`.`pistas` (
  `id_pistas` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `dificultad` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `longitud` VARCHAR(45) NOT NULL,
  `fk_estaciones` INT NOT NULL,
  PRIMARY KEY (`id_pistas`),
  INDEX `fk_pistas_estaciones_idx` (`fk_estaciones` ASC) VISIBLE,
  CONSTRAINT `fk_pistas_estaciones`
    FOREIGN KEY (`fk_estaciones`)
    REFERENCES `esquiar`.`estaciones` (`id_estaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esquiar`.`usuarios_db`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquiar`.`usuarios_db` (
  `id_usuarios_db` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usuarios_db`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esquiar`.`usuarios_estaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquiar`.`usuarios_estaciones` (
  `fk_usuarios` INT NOT NULL,
  `fk_estaciones` INT NOT NULL,
  `id_usuarios_estaciones` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_usuarios_db_has_estaciones_estaciones1_idx` (`fk_estaciones` ASC) VISIBLE,
  INDEX `fk_usuarios_db_has_estaciones_usuarios_db1_idx` (`fk_usuarios` ASC) VISIBLE,
  PRIMARY KEY (`id_usuarios_estaciones`),
  CONSTRAINT `fk_usuarios_db_has_estaciones_usuarios_db1`
    FOREIGN KEY (`fk_usuarios`)
    REFERENCES `esquiar`.`usuarios_db` (`id_usuarios_db`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_db_has_estaciones_estaciones1`
    FOREIGN KEY (`fk_estaciones`)
    REFERENCES `esquiar`.`estaciones` (`id_estaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esquiar`.`pistas_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `esquiar`.`pistas_usuarios` (
  `fk_pistas` INT NOT NULL,
  `fk_usuarios` INT NOT NULL,
  `id_pistas_usuarios` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_pistas_has_usuarios_db_usuarios_db1_idx` (`fk_usuarios` ASC) VISIBLE,
  INDEX `fk_pistas_has_usuarios_db_pistas1_idx` (`fk_pistas` ASC) VISIBLE,
  PRIMARY KEY (`id_pistas_usuarios`),
  CONSTRAINT `fk_pistas_has_usuarios_db_pistas1`
    FOREIGN KEY (`fk_pistas`)
    REFERENCES `esquiar`.`pistas` (`id_pistas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pistas_has_usuarios_db_usuarios_db1`
    FOREIGN KEY (`fk_usuarios`)
    REFERENCES `esquiar`.`usuarios_db` (`id_usuarios_db`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
